### ISSUE TITLE
Cannot Install using gradle

### ISSUE THREAD

**Issue by aslampr07** [Cleveroad/CycleMenu#10]
After adding the to gradle i am getting this error on build

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processDebugResources'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
Output:  /home/aslampr07/Desktop/UrbanMeals/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
/home/aslampr07/Desktop/UrbanMeals/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
/home/aslampr07/Desktop/UrbanMeals/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1343: error: resource android:attr/fontVariationSettings not found.
/home/aslampr07/Desktop/UrbanMeals/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1344: error: resource android:attr/ttcIndex not found.
error: failed linking references.

Command: /home/aslampr07/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-linux.jar/1b573c3e2823472ba1fbd3a5933e11f3/aapt2-3.2.1-4818971-linux/aapt2 link -I\
        /home/aslampr07/Android/Sdk/platforms/android-27/android.jar\
        --manifest\
        /home/aslampr07/Desktop/UrbanMeals/app/build/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
        -o\
        /home/aslampr07/Desktop/UrbanMeals/app/build/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
        -R\
        @/home/aslampr07/Desktop/UrbanMeals/app/build/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
        --auto-add-overlay\
        --java\
        /home/aslampr07/Desktop/UrbanMeals/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
        --custom-package\
        com.urbanmeals.client.urbanmeals\
        -0\
        apk\
        --output-text-symbols\
        /home/aslampr07/Desktop/UrbanMeals/app/build/intermediates/symbols/debug/R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.1-4818971-linux Daemon #0
Output:  /home/aslampr07/.gradle/caches/transforms-1/files-1.1/appcompat-v7-28.0.0.aar/80b9b62e4074565f92e856fac1c574cb/res/values-v28/values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.
    
/home/aslampr07/Desktop/UrbanMeals/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.
    
/home/aslampr07/.gradle/caches/transforms-1/files-1.1/design-28.0.0.aar/dd5bdbc87e9b5f814357dcf89aacdefa/res/values/values.xml:161:5-202: AAPT: error: resource android:attr/fontVariationSettings not found.
    
/home/aslampr07/.gradle/caches/transforms-1/files-1.1/design-28.0.0.aar/dd5bdbc87e9b5f814357dcf89aacdefa/res/values/values.xml:161:5-202: AAPT: error: resource android:attr/ttcIndex not found.
    
error: failed linking references.
Command: /home/aslampr07/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-linux.jar/1b573c3e2823472ba1fbd3a5933e11f3/aapt2-3.2.1-4818971-linux/aapt2 link -I\
        /home/aslampr07/Android/Sdk/platforms/android-27/android.jar\
        --manifest\
        /home/aslampr07/Desktop/UrbanMeals/app/build/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
        -o\
        /home/aslampr07/Desktop/UrbanMeals/app/build/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
        -R\
        @/home/aslampr07/Desktop/UrbanMeals/app/build/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
        --auto-add-overlay\
        --java\
        /home/aslampr07/Desktop/UrbanMeals/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
        --custom-package\
        com.urbanmeals.client.urbanmeals\
        -0\
        apk\
        --output-text-symbols\
        /home/aslampr07/Desktop/UrbanMeals/app/build/intermediates/symbols/debug/R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.1-4818971-linux Daemon #0
	at com.android.build.gradle.internal.res.Aapt2ErrorUtils.rewriteException(Aapt2ErrorUtils.kt:97)
	at com.android.build.gradle.internal.res.Aapt2ErrorUtils.rewriteLinkException(Aapt2ErrorUtils.kt:73)
	at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.invokeAaptForSplit(LinkApplicationAndroidResourcesTask.java:527)
	at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.doFullTaskAction(LinkApplicationAndroidResourcesTask.java:275)
	at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
	... 33 more
Caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
Output:  /home/aslampr07/Desktop/UrbanMeals/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
/home/aslampr07/Desktop/UrbanMeals/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
/home/aslampr07/Desktop/UrbanMeals/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1343: error: resource android:attr/fontVariationSettings not found.
/home/aslampr07/Desktop/UrbanMeals/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1344: error: resource android:attr/ttcIndex not found.
error: failed linking references.

Command: /home/aslampr07/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-linux.jar/1b573c3e2823472ba1fbd3a5933e11f3/aapt2-3.2.1-4818971-linux/aapt2 link -I\
        /home/aslampr07/Android/Sdk/platforms/android-27/android.jar\
        --manifest\
        /home/aslampr07/Desktop/UrbanMeals/app/build/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
        -o\
        /home/aslampr07/Desktop/UrbanMeals/app/build/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
        -R\
        @/home/aslampr07/Desktop/UrbanMeals/app/build/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
        --auto-add-overlay\
        --java\
        /home/aslampr07/Desktop/UrbanMeals/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
        --custom-package\
        com.urbanmeals.client.urbanmeals\
        -0\
        apk\
        --output-text-symbols\
        /home/aslampr07/Desktop/UrbanMeals/app/build/intermediates/symbols/debug/R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.1-4818971-linux Daemon #0
	at com.android.builder.internal.aapt.v2.Aapt2DaemonImpl.doLink(Aapt2DaemonImpl.kt:177)
	at com.android.builder.internal.aapt.v2.Aapt2Daemon.link(Aapt2Daemon.kt:103)
	at com.android.builder.internal.aapt.v2.Aapt2DaemonManager$LeasedAaptDaemon.link(Aapt2DaemonManager.kt:176)
	at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:823)
	at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.invokeAaptForSplit(LinkApplicationAndroidResourcesTask.java:525)
	... 50 more


```

**Comment by VadimHalimendikCr** [comment]
@aslampr07 Thanks for your feedback, the problem was in readme file, just change package of `CycleMenuWidget` in your layout according updated readme. With best regards Cleveroad team!
